---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: 雖然 REST 確立了一套通用的技術和最佳實踐，但每個 API 的細節可能會因設計選擇而異。在使用ONTAP Select Deploy API 之前，您應該了解該 API 的詳細資訊和操作特性。 
---
= ONTAP Select Deploy API 基本操作特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
雖然 REST 確立了一套通用的技術和最佳實踐，但每個 API 的細節可能會因設計選擇而異。在使用ONTAP Select Deploy API 之前，您應該了解該 API 的詳細資訊和操作特性。



== 虛擬機器管理程式主機與ONTAP Select節點

_虛擬機器管理程式主機_是託管ONTAP Select虛擬機器的核心硬體平台。當ONTAP Select虛擬機器部署在虛擬機器管理程式主機上並處於活動狀態時，該虛擬機器將被視為 ONTAP Select 節點。在 Deploy REST API 版本 3 中，主機物件和節點物件是獨立且不同的。這允許一對多關係，其中一個或多個ONTAP Select節點可以在同一虛擬機器管理程式主機上運行。



== 物件標識符

每個資源實例或物件在建立時都會指派一個唯一識別碼。這些標識符在ONTAP Select Deploy 的特定實例中是全域唯一的。在發出建立新物件實例的 API 呼叫後，關聯的 id 值將傳回給呼叫者。 `location` HTTP回應頭。您可以提取標識符，並在後續呼叫中引用資源實例時使用它。


NOTE: 物件標識符的內容和內部結構可能隨時變更。在引用關聯物件時，應僅在適用的 API 呼叫中根據需要使用這些標識符。



== 請求標識符

每個成功的 API 請求都會被指派一個唯一的識別碼。傳回的標識符 `request-id`相關HTTP響應的頭部。您可以使用請求識別碼來統稱單一特定 API 請求-回應事務的活動。例如，您可以根據請求 ID 檢索交易的所有事件訊息。



== 同步和異步調用

伺服器執行從客戶端收到的 HTTP 請求主要有兩種方式：

* 同步伺服器立即執行請求並以狀態代碼 200、201 或 204 回應。
* 非同步：伺服器接受請求並以狀態碼 202 回應。這表示伺服器已接受客戶端請求並啟動後台任務以完成該請求。最終的成功或失敗情況無法立即確定，必須透過其他 API 呼叫來確定。




== 確認長期運行作業的完成

通常，任何需要很長時間才能完成的操作都會使用伺服器上的後台任務非同步處理。使用 Deploy REST API，每個後台任務都由一個 Job 物件固定，該物件追蹤任務並提供資訊（例如當前狀態）。建立後台任務後，HTTP 回應中會傳回一個 Job 物件（包含其唯一識別碼）。

您可以直接查詢 Job 物件來確定相關 API 呼叫是否成功。有關更多信息，請參閱_使用 Job 物件進行非同步處理_。

除了使用 Job 物件之外，還有其他方法可以確定請求的成功或失敗，包括：

* 事件訊息您可以使用原始回應傳回的請求 ID 來擷取與特定 API 呼叫關聯的所有事件訊息。事件訊息通常包含成功或失敗的指示，在偵錯錯誤情況時也很有用。
* 資源狀態或狀況 有些資源維持一個狀態或狀況值，您可以查詢該狀態或狀況值來間接確定請求的成功或失敗。




== 安全

Deploy API 使用以下安全技術：

* 傳輸層安全性 (TLS)：Deploy 伺服器和用戶端之間透過網路傳送的所有流量均透過 TLS 加密。不支援在未加密的通道上使用 HTTP 協定。支援 TLS 1.2 版本。
* HTTP 驗證 每個 API 交易都使用基本驗證。每個請求都會新增一個 HTTP 標頭，其中包含以 base64 字串形式表示的使用者名稱和密碼。

