---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 首先熟悉適用於ONTAP Select環境的常規網路概念。然後，探索單節點和多節點叢集的具體特性和選項。 
---
= ONTAP Select網路概念與特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
首先熟悉適用於ONTAP Select環境的常規網路概念。然後，探索單節點和多節點叢集的具體特性和選項。



== 實體網路

實體網路主要透過提供底層第二層交換基礎架構來支援ONTAP Select叢集部署。與實體網路相關的配置包括虛擬機器管理程式主機和更廣泛的交換網路環境。



=== 主機 NIC 選項

每個ONTAP Select虛擬機器管理程式主機必須配置兩個或四個實體連接埠。具體配置取決於以下幾個因素：

* 叢集是否包含一個或多個ONTAP Select主機
* 使用哪種虛擬機器管理程式作業系統
* 如何配置虛擬交換機
* 連結是否使用 LACP




=== 實體交換器配置

您必須確保實體交換器的配置支援ONTAP Select部署。實體交換器與基於虛擬機器管理程式的虛擬交換器整合在一起。您選擇的具體配置取決於多種因素。主要考慮因素包括：

* 您將如何保持內部和外部網路之間的分離？
* 您會保持資料和管理網路之間的分離嗎？
* 二層 VLAN 將如何配置？




== 邏輯網絡

ONTAP Select使用兩個不同的邏輯網絡，根據類型分離流量。具體來說，流量可以在叢集內的主機之間流動，也可以流向叢集外的儲存用戶端和其他電腦。虛擬機器管理程式管理的虛擬交換器有助於支援邏輯網路。



=== 內部網路

在多節點叢集部署中，各個ONTAP Select節點使用獨立的「內部」網路進行通訊。此網路不會暴露給ONTAP Select叢集中的節點，也不會在節點外部使用。


NOTE: 內部網路僅存在於多節點叢集中。

內部網路具有以下特點：

* 用於處理ONTAP叢集內流量，包括：
+
** 簇
** 高可用性互連 (HA-IC)
** RAID 同步鏡像 (RSM)


* 基於VLAN的單二層網絡
* 靜態 IP 位址由ONTAP Select分配：
+
** 僅限 IPv4
** 未使用 DHCP
** 鏈路本地地址


* MTU 大小預設為 9000 字節，可在 7500-9000 範圍內調整（含）




=== 外部網路

外部網路處理ONTAP Select叢集節點與外部儲存客戶端以及其他電腦之間的流量。外部網路是每個叢集部署的一部分，具有以下特點：

* 用於處理ONTAP流量，包括：
+
** 資料（NFS、CIFS、iSCSI）
** 管理（叢集和節點；可選 SVM）
** 集群間（可選）


* 選用支援 VLAN：
+
** 資料連接埠組
** 管理連接埠組


* 根據管理員的配置選擇指派的 IP 位址：
+
** IPv4 或 IPv6


* MTU 大小預設為 1500 位元組（可調整）


外部網路存在各種規模的集群。



== 虛擬機器網路環境

虛擬機器管理程式主機提供了多種網路功能。

ONTAP Select依賴透過虛擬機器公開的以下功能：

虛擬機器連接埠:: ONTAP Select有多個連接埠可供使用。這些連接埠的分配和使用取決於多種因素，包括群集的大小。
虛擬交換機:: 虛擬機器管理程式環境中的虛擬交換器軟體（無論是 vSwitch (VMware) 或 Open vSwitch (KVM)）都會將虛擬機器公開的連接埠與實體乙太網路 NIC 連接埠連接起來。您必須根據環境為每個ONTAP Select主機配置一個 vSwitch。

