---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 部署ONTAP Select叢集後，您可以根據需要使用標準ONTAP軟體升級程式升級每個節點的ONTAP映像。 
---
= 升級ONTAP Select節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署ONTAP Select叢集後，您可以根據需要升級叢集中每個節點的ONTAP映像。


CAUTION: 您無法使用 Deploy 管理實用程式來升級現有的ONTAP Select節點。 Deploy實用程式只能用於建立新的ONTAP Select叢集。



== 一般程序

從高層次來看，您應該使用以下步驟來升級現有的ONTAP Select節點。

.步驟
. 存取 link:https://mysupport.netapp.com/site/downloads/["NetApp 支援網站下載"^] 頁面。
. 向下捲動並選擇 *ONTAP Select Image*。
. 選擇所需的安裝映像版本。
. 查看最終用戶許可協議 (EULA) 並選擇*接受並繼續*。
. 選擇並下載適當的 *ONTAP Select Image Upgrade* 套件。視需要回應所有提示。
+
在升級 ONTAP Select 節點之前，請查看 link:reference_release_notes.html["發行說明"] 以取得其他資訊和任何必要的程序。

. 使用ONTAP Select升級文件，透過標準ONTAP升級流程升級ONTAP Select節點。有關支援的升級路徑的信息，請參閱link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["支援的ONTAP升級路徑"^]。




== 還原ONTAP Select節點

您無法將ONTAP Select節點還原到其最初安裝時的版本之前的版本。例如：

初始安裝的是ONTAP Select 9.16.1。:: 您可以將節點升級到版本 9.17.1，如果需要，再還原到版本 9.16.1。
初始安裝的是ONTAP Select 9.17.1。:: 由於之前沒有安裝過舊版本，因此無法回滾。




== 使用 VMXNET3 網路驅動程式

VMXNET3 是 VMware ESXi 上新叢集部署隨附的預設網路驅動程式。如果您升級執行ONTAP Select 9.4 或更早版本的現有ONTAP Select節點，則網路驅動程式不會自動升級。您必須手動升級到 VMXNET3。請聯絡NetApp支援以取得升級方面的協助。

.相關資訊
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP升級概述"^]
