---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: '表述性狀態傳輸 (REST) 是一種用於建立分散式 Web 應用程式的樣式。當應用於 Web 服務 API 的設計時，它可以建立一套用於公開基於伺服器的資源並管理其狀態的技術和最佳實踐。它使用主流協定和標準，為部署和管理ONTAP Select叢集提供靈活的基礎。' 
---
= 用於部署和管理ONTAP Select叢集的 REST Web 服務基礎
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
表述性狀態傳輸 (REST) 是一種用於建立分散式 Web 應用程式的樣式。當應用於 Web 服務 API 的設計時，它可以建立一套用於公開基於伺服器的資源並管理其狀態的技術和最佳實踐。它使用主流協定和標準，為部署和管理ONTAP Select叢集提供靈活的基礎。



== 建築與經典約束

REST 理論由 Roy Fielding 在博士論文中正式闡述。 https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["論文"] 2000年畢業於加州大學爾灣分校。它透過一系列約束定義了一種架構風格，這些約束共同改進了基於Web的應用程式及其底層協定。這些約束基於客戶端/伺服器架構，使用無狀態通訊協議，建構了一個RESTful Web服務應用程式。



== 資源和國家代表

資源是基於 Web 系統的基本元件。在建立 REST Web 服務應用程式時，早期設計任務包括：

* 識別系統或基於伺服器的資源。每個系統都會使用和維護資源。資源可以是文件、業務事務、流程或管理實體。基於 REST Web 服務設計應用程式的首要任務之一就是識別資源。
* 資源狀態及相關狀態操作的定義：資源始終處於有限數量的狀態之一。必須明確定義這些狀態以及用於影響狀態變化的相關操作。


用戶端和伺服器之間交換訊息，根據通用 CRUD（建立、讀取、更新和刪除）模型存取和變更資源的狀態。



== URI 端點

每個 REST 資源都必須使用定義明確的尋址方案進行定義和提供。資源所在和識別的端點使用統一資源標識符 (URI)。 URI提供了一個通用框架，用於為網路中的每個資源建立唯一名稱。統一資源定位符 (URL) 是一種用於 Web 服務識別和存取資源的 URI。資源通常以類似文件目錄的層級結構公開。



== HTTP 郵件

超文本傳輸協定 (HTTP) 是 Web 服務用戶端和伺服器用來交換資源請求和回應訊息的協定。在設計 Web 服務應用程式的過程中，HTTP 動詞（例如 GET 和 POST）會被對應到資源及其對應的狀態管理操作。

HTTP 是無狀態的。因此，為了將一組相關的請求和回應關聯到一個事務下，必須在請求/回應資料流攜帶的 HTTP 標頭中包含附加資訊。



== JSON 格式

雖然資訊可以透過多種方式在客戶端和伺服器之間建置和傳輸，但最受歡迎的選項（以及與部署 REST API 一起使用的選項）是 JavaScript 物件表示法 (JSON)。 JSON是一種行業標準，用於以純文字表示簡單資料結構，並用於傳輸描述資源的狀態資訊。
