---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 容量池許可模型與容量層模型不同。它不是為每個節點分配專用的儲存容量，而是將儲存容量分配給一個池，並在多個節點之間共用。為了支援容量池模型，我們創建了其他元件和流程。 
---
= ONTAP Select容量池許可模式的操作詳細信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量池許可模型與容量層模型不同。它不是為每個節點分配專用的儲存容量，而是將儲存容量分配給一個池，並在多個節點之間共用。為了支援容量池模型，我們創建了其他元件和流程。



== 許可證管理器

許可證管理器在每個 Deploy 管理實用程式實例中作為單獨的程序運行。許可證管理員提供的一些功能包括：

* 根據容量池許可證序號為每個節點產生唯一的二十位元序號
* 根據ONTAP Select節點的請求，從共用容量池建立容量租約
* 透過 Deploy 使用者介面報告池使用情況資訊




== 租賃特徵

使用容量池許可證的節點上為每個資料聚合分配的儲存必須具有關聯的租約。節點請求儲存租約，如果容量可用，許可證管理器將以租約回應。每個租約都具有以下顯式或隱式屬性：

* 許可證管理器 每個ONTAP Select節點都與一個許可證管理器實例關聯
* 容量池 每個ONTAP Select節點都與一個容量池關聯
* 儲存分配 在租約中分配特定的容量值
* 到期日期和時間租約期限為一小時至七天，視使用者設定而定。




== 許可證鎖定ID

每個許可證管理器實例，以及每個對應的 Deploy 實用程式實例，都使用一個唯一的 128 位元編號進行識別。此編號與九位數容量池許可證序號結合，將池鎖定到特定的許可證管理器實例（實際上是一個 Deploy 實例）。您必須在NetApp支援網站產生NetApp授權檔 (NLF) 時提供這兩個值。

您可以透過以下方式使用 Web 使用者介面來確定 Deploy 執行個體的授權鎖定 ID：

* 首次登入 Deploy 時會顯示此頁面。您也可以點擊頁面右上角的下拉方塊並選擇「開始使用」來顯示此頁面。 LLID顯示在「新增許可證」部分。
* 管理 按一下頁面頂部的「*管理*」選項卡，然後按一下「*系統*」和「*設定*」。




== 基本租賃業務

每次建立、擴充或變更資料聚合時， ONTAP Select節點都必須尋找或要求有效的容量租約。可以使用先前請求中獲取的仍然有效的租約，也可以根據需要請求新的租約。 ONTAPONTAP Select節點執行下列步驟來尋找容量池租約：

. 如果節點上存在現有租約，則只要滿足以下所有條件，就會使用該租約：
+
** 租約尚未到期
** 聚合的儲存請求未超出租賃容量


. 如果找不到現有租約，節點將向許可證管理器要求新的租約。




== 將儲存容量返回容量池

儲存容量根據需要從容量池中分配，每個新請求都會減少池中的可用儲存空間。儲存容量在以下幾種情況下會返回池中：

* 資料聚合的租約已到期，且節點未續約
* 資料集合已刪除



NOTE: 如果刪除ONTAP Select虛擬機，所有活動租約仍然有效，直到到期。到期後，容量將返回池中。
