---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: ONTAP Select Deploy 是一款用於部署和管理ONTAP Select叢集的管理實用程式。 Deploy 
---
= ONTAP Select部署
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 是一款用於部署和管理ONTAP Select叢集的管理實用程式。 Deploy打包為 Linux 虛擬機，您必須在建立ONTAP Select叢集之前安裝它。



== 核心功能

Deploy 管理公用程式執行以下核心功能：

* 記錄部署ONTAP Select 的每個虛擬機器管理程式主機的詳細信息
* 配置主機並安裝所需的許可證
* 部署和管理ONTAP Select集群
* 維護ONTAP Select叢集和主機的清單
* 收集AutoSupport資料並將其發送到NetApp
* 維護一組內部ONTAP Select節點映像
* 支援虛擬機器管理程式特定的命令格式和協議




== 存取部署實用程式的方法

存取 Deploy 管理實用程式時，您有多個選項可用。所有外部介面的功能相同。您應該選擇最符合您特定部署目標和要求的存取選項。在所有情況下，您都必須使用管理員帳戶和有效密碼登入。



=== Web圖形使用者介面

您可以透過現代 Web 瀏覽器存取 Deploy 實用程式。 WebUI 提供了直覺易用的介面，在大多數情況下，它將是您使用該實用程式時的主要介面。



=== 命令列介面

可透過管理 Shell 存取基於文字的命令列介面。您可以透過以下方式存取 CLI 管理 Shell：

* 安全殼 (SSH)
* 虛擬機器控制台


您通常會在安裝和初始設定過程中使用虛擬機器控制台。但是，在大多數情況下，SSH 提供了更靈活、更便利的選項。



=== REST Web 服務 API

向外部用戶端公開的 REST Web 服務 API 為連接到 Deploy 實用程式提供了另一種選擇。您可以使用任何支援 REST Web 服務的主流程式語言或工具來存取該 API。常用的選擇包括：

* Python
* Java
* 捲曲


使用程式設計或腳本語言可以實現ONTAP Select叢集部署和管理的自動化。



=== ONTAP Select線上文件網頁

在 Deploy 公用程式中顯示線上文件網頁是存取 REST Web 服務 API 的另一種方法。但是，您無需使用程式語言，而是使用瀏覽器透過頁面存取管理 API。提供以下功能：

* REST Web 服務 API 中每個呼叫的詳細描述
* 手動發出任何 API 呼叫的能力


您可以使用 Deploy 虛擬機器的 IP 或網域存取線上文件頁面。若要顯示該頁面，請在瀏覽器中輸入下列格式的 URL（將 URL 替換為您的 Deploy VM 執行個體的對應 IP 位址或網域名稱）： `\http://<ip_address>/api/ui`
