---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: 您應考慮幾個與ONTAP Select主機儲存相關的規劃問題。 
---
= ONTAP Select儲存與 RAID 注意事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應考慮幾個與ONTAP Select主機儲存相關的規劃問題。


NOTE: 外部儲存支援資訊概述如下：link:reference_plan_ots_vnas.html["ONTAP Select vNAS 要求"] 。



== 硬體 RAID 控制器需求

部署ONTAP Select 的虛擬機器管理程式主機上的 RAID 控制器必須符合幾個要求。


NOTE: 使用硬體 RAID 控制器或ONTAP Select提供的軟體 RAID 功能時，執行ONTAP Select 的主機需要本機實體磁碟機。如果您使用ONTAP Select vNAS 解決方案存取外部存儲，則不會使用本機 RAID 控制器和軟體 RAID 功能。

RAID 控制器的最低要求包括：

* 12 Gbps 吞吐量
* 512 MB 內部電池供電或快閃記憶體（超級電容）緩存
* 以回寫模式配置：
+
** 啟用故障回復模式以「直寫」（如果支援）
** 啟用“始終預讀”策略（如果支援）


* RAID 控制器後面的所有本機磁碟都應配置為單一 RAID 群組；如果需要，可以使用多個 RAID 控制器：
+
** 停用 RAID 群組的本機磁碟機緩存，這對於維護資料完整性至關重要。


* 必須根據以下準則執行 LUN 設定：
+
** 如果 RAID 群組大小超過最大 LUN 大小 64 TB，則應配置多個大小相同的 LUN，以使用 RAID 群組內的所有可用儲存空間。
** 如果 RAID 群組大小小於最大 LUN 大小 64 TB，則應設定一個使用 RAID 群組內所有可用儲存空間的 LUN。






== 軟體 RAID 要求

在虛擬機器管理程式上部署ONTAP Select叢集時，您可以利用ONTAP Select提供的軟體 RAID 功能，而無需使用本機硬體 RAID 控制器。在使用軟體 RAID 部署叢集之前，您必須注意一些要求和限制。



=== 一般要求

軟體 RAID 部署環境必須符合以下核心要求：

* VMware ESXi 7.0 GA（內部版本 15843807）或更高版本
* ONTAP Select Premium 許可證或更高版本
* 僅限本機 SSD 驅動器
* 將系統磁碟與根和資料聚合分離
* 主機上沒有硬體 RAID 控制器



NOTE: 如果存在硬體 RAID 控制器，請參閱link:concept_stor_concepts_chars.html["深層存儲"]本節用於說明其他配置要求。



=== ESXi 特定要求

* VMware ESXi 7.0 GA（內部版本 15843807）或更高版本
* 不支援 VMware VMotion、HA 和 DRS
* 您無法將軟體 RAID 與從ONTAP Select 9.4 或更早版本升級的節點一起使用。如果是這種情況，您需要建立一個新節點來部署軟體 RAID。




=== KVM 特定要求

還有一些特定的軟體包配置要求。參見link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linux 伺服器的準備"]了解更多信息，請執行以下步驟。

媒體對 KVM 的期望:: 所使用的 SSD 快閃記憶體裝置必須符合以下額外要求：
+
--
* SSD 設備必須透過以下方法準確、持續地向 Linux 主機報告自身情況：
+
** # cat /sys/block/<裝置>/queue/rotational
+
這些命令報告的值必須為“0”。



* 預計設備將連接到 HBA，或在某些情況下連接到配置為 JBOD 模式的 RAID 控制器。使用 RAID 控制器時，設備功能必須透過主機傳遞，且不得覆寫任何 RAID 功能。在 JBOD 模式下使用 RAID 控制器時，您應該查看 RAID 文件或根據需要聯絡供應商，以確保裝置將轉速報告為「0」。
* 有兩個獨立的儲存組件：
+
** 虛擬機器存儲
+
這是一個 LVM 池（儲存池），包含用於託管ONTAP Select虛擬機器的系統資料。此 LVM 池必須由高耐用性快閃裝置支援，可以是 SAS、SATA 或 NVMe。建議使用 NVMe 設備以提高效能。

** 資料磁碟
+
這是一組用於資料管理的 SAS 或 SATA SSD 磁碟機。 SSD設備應為企業級且耐用。不支援 NVMe 介面。



* 所有設備必須採用 512BPS 格式化。


--




=== ONTAP Select節點配置

您必須如下設定每個ONTAP Select節點和虛擬機器管理程式主機，以將系統磁碟與根和資料聚合分開：

* 建立系統儲存池您必須為ONTAP Select系統資料建立一個儲存池。您必須在配置ONTAP Select節點的過程中連接儲存池。
* 連接必要的實體磁碟 虛擬機器管理程式主機必須連接所需的 SSD 磁碟，並且可供ONTAP Select虛擬機器使用。這些驅動器用於儲存根聚合和資料聚合。您必須在配置ONTAP Select節點的過程中連接儲存磁碟。




== 儲存容量限制

作為規劃ONTAP Select部署的一部分，您應該了解與儲存分配和使用相關的限制。

最重要的儲存限制如下。您還應該查看link:https://mysupport.netapp.com/matrix/["互通性矩陣工具"^]更多詳細信息，敬請垂詢。


TIP: ONTAP Select強制實施多項與儲存分配和使用相關的限制。在部署ONTAP Select叢集或購買許可證之前，您應該熟悉這些限制。參見link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["執照"]更多資訊請參閱相關部分。



=== 計算原始儲存容量

ONTAP Select儲存容量對應於連接到ONTAP Select虛擬機器的虛擬資料磁碟和根磁碟的總允許大小。分配容量時應考慮這一點。



=== 單節點叢集的最小儲存容量

單節點叢集中為節點分配的儲存池最小大小為：

* 評估：500 GB
* 生產：1.0 TB


生產部署的最低分配包括 1 TB 用於用戶數據，加上各種ONTAP Select內部進程使用的約 266 GB，這被視為必需的開銷。



=== 多節點叢集的最小儲存容量

多節點叢集中每個節點分配的儲存池最小大小為：

* 評估：1.9 TB
* 生產：2.0 TB


生產部署的最低分配包括 2 TB 用於用戶數據，加上各種ONTAP Select內部進程使用的約 266 GB，這被視為必需的開銷。

[NOTE]
====
HA 對中的每個節點必須具有相同的儲存容量。

估算 HA 對的儲存量時，必須考慮所有聚合（根聚合和資料聚合）都已鏡像。因此，聚合的每個叢都會消耗相同的儲存量。

例如，在建立 2 TB 聚合時，它會將 2 TB 指派給兩個 plex 實例（plex0 為 2 TB，plex1 為 2 TB），或將總授權儲存量的 4 TB 指派給兩個 plex 實例。

====


=== 儲存容量和多個儲存池

使用本機直連儲存、VMware vSAN 或外部儲存陣列時，您可以將每個ONTAP Select節點配置為使用最多 400 TB 的儲存空間。但是，在使用直連儲存或外部儲存陣列時，單一儲存池的最大大小為 64 TB。因此，如果您打算在這些情況下使用超過 64 TB 的儲存空間，則必須如下指派多個儲存池：

* 在叢集建立過程中指派初始儲存池
* 透過分配一個或多個額外的儲存池來增加節點存儲



NOTE: 每個儲存池中都會留出 2% 的緩衝區未使用，並且無需容量許可證。上限，否則ONTAP Select不會使用此儲存空間。如果指定了容量上限，則將使用該儲存空間，除非指定的容量在 2% 的緩衝區內。需要此緩衝區是為了防止在嘗試分配儲存池中的所有空間時偶爾發生的錯誤。



=== 儲存容量和 VMware vSAN

使用 VMware vSAN 時，資料儲存區可以大於 64 TB。但是，在建立ONTAP Select叢集時，您最初最多只能指派 64 TB 的儲存空間。叢集建立完成後，您可以從現有的 vSAN 資料儲存區指派額外的儲存空間。 ONTAPONTAP Select可使用的 vSAN 資料儲存區容量取決於虛擬機器儲存策略集。



=== 最佳實踐

您應該考慮有關虛擬機器管理程式核心硬體的以下建議：

* 單一ONTAP Select聚合中的所有磁碟機應為相同類型。例如，不應在同一個聚合中混用 HDD 驅動器和 SSD 驅動器。




== 根據平台許可證的額外磁碟機要求

根據平台許可證的提供，您選擇的磁碟機受到限制。


NOTE: 使用本機 RAID 控制器和磁碟機以及軟體 RAID 時，磁碟機要求適用。這些要求不適用於透過ONTAP Select vNAS 解決方案存取的外部儲存。

.標準
* 8 到 60 個內部 HDD（NL-SAS、SATA、10K SAS）


.優質的
* 8 到 60 個內部 HDD（NL-SAS、SATA、10K SAS）
* 4 至 60 個內部 SSD


.進階加大尺寸
* 8 到 60 個內部 HDD（NL-SAS、SATA、10K SAS）
* 4 至 60 個內部 SSD
* 4 到 14 個內部 NVMe



NOTE: 高級授權（僅限 SSD）和高級 XL 授權（SSD 或 NVMe）支援具有本機 DAS 磁碟機的軟體 RAID。



== 帶有軟體 RAID 的 NVMe 驅動器

您可以設定軟體 RAID 以使用 NVMe SSD 硬碟。您的環境必須符合以下要求：

* 使用受支援的部署管理實用程式ONTAP Select
* Premium XL 平台許可證或 90 天評估許可證
* VMware ESXi 6.7 或更高版本
* 符合規範 1.0 或更高版本的 NVMe 設備


在使用 NVMe 驅動器之前，您需要手動配置它們。看link:task_chk_nvme_configure.html["配置主機以使用 NVMe 驅動器"]了解更多。
