---
sidebar: sidebar 
permalink: reference_faq.html 
keywords: faq, frequently asked questions 
summary: 尋找有關ONTAP Select 的常見問題的答案。 
---
= ONTAP Select常見問題解答
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以找到有關ONTAP Select 的常見問題的解答。

[NOTE]
====
從ONTAP Select 9.14.1 開始，已復原對 KVM 虛擬機器管理程式的支援。先前， ONTAP Select 9.10.1 中已移除在 KVM 虛擬機管理程式上部署新叢集的支持，而ONTAP Select 9.11.1 中已移除對管理現有 KVM 叢集和主機（離線或移除除外）的支援。

====


== 一般的

有幾個一般性的問題和答案。

.ONTAP Select Deploy 和ONTAP Select有什麼差別？
ONTAP Select Deploy 是用於建立ONTAP Select叢集的實用程式。目前， ONTAP Select Deploy 是建立生產叢集的唯一方法。 ONTAPONTAP Select Deploy 也可用於建立評估版 Select 叢集，以便客戶測試和記錄生產部署的實際步驟。 ONTAPONTAP Select Deploy 還可以使用適當的容量層許可證將評估版集群轉換為生產集群，該許可證的容量足以覆蓋評估期間佔用的空間。

ONTAP Select Deploy 是一個包含ONTAP Select映像的虛擬機器。在叢集安裝期間， ONTAP Select Deploy 會強制執行多項檢查，以協助確保符合ONTAP Select 的最低要求。 ONTAPONTAP Select Deploy 虛擬機器和 Select 叢集可以單獨升級。

.如何解決ONTAP Select的效能問題？
與FAS上的ONTAP類似，應使用 perfstat 公用程式收集效能資料。以下是範例命令：

[listing]
----
perfstat8 –i N,m -t <sample time in minutes> --verbose --nodes=<filer IP> --diag-passwd=abcxyz --mode="cluster-mode" > <name of output file>
----
.如何存取ONTAP Select Deploy 的 Swagger API 頁面？
[listing]
----
http://<Deploy-IP-Address/api/ui
----

NOTE: API v3 版本不向後相容於先前的 API 版本。新的 API 程式已發布 https://library.netapp.com/ecm/ecm_download_file/ECMLP2845694["現場門戶"^]。

.ONTAP Select VM 可以使用 VMware 或其他第三方快照進行備份嗎？
不可以。 ONTAP ONTAP Select VM 使用獨立持久驅動器，這些驅動器不在基於 VMware 的快照範圍內。 ONTAPONTAP Select唯一支援的備份方法是SnapMirror或SnapVault。

.對於本常見問題中未涵蓋的問題，我可以在哪裡獲得解答？
接觸link:mailto:ng-ses-ontap-select@netapp.com["ng-ses-ontap-select@netapp.com"]。



== 許可、安裝、升級和恢復

有幾個問題和答案涉及許可證、安裝、升級和恢復。

.ONTAP Select和ONTAP Select Deploy 可以單獨升級嗎？
是的。ONTAP Select Deploy 實用程式可以獨立於ONTAP Select叢集進行升級。同樣，Select 叢集也可以獨立於ONTAP Select Deploy 實用程式進行升級。

.ONTAP Select是否可以使用與FAS叢集相同的步驟進行升級？
是的，Select 叢集的升級過程與FAS叢集的升級相同，儘管ONTAP Select升級二進位檔案是與FAS上的ONTAP升級二進位檔案分開下載的。

.是否可以使用與FAS叢集相同的過程來復原ONTAP Select ？
是的， ONTAP Select叢集的還原過程與FAS叢集的還原過程幾乎相同。但也存在一些差異：

* 只有升級的ONTAP Select實例可以還原，並且只能還原到原始安裝版本。新安裝的實例無法還原到較舊的程式碼版本，即使ONTAP Select通常支援該較舊版本。
* 對於使用軟體 RAID 的ONTAP Select (KVM) 和ONTAP Select (ESX)，無法還原至不支援軟體 RAID 的早期版本。此外，在 ESX 上新安裝的ONTAP Select 9.5 或更高版本使用 VMXNET3 網路驅動程序，並且（如果可能）也會使用 vNMVE 驅動程式。這些新安裝無法還原到ONTAP Select的早期版本。
* 如果ONTAP Select VM 也升級為大型實例（使用 Premium XL 授權），則不支援還原至 9.6 之前的版本，因為早期版本中不提供大型執行個體功能。


.ONTAP MetroCluster SDS 是否至少需要 Premium 授權？
是的。

.安裝後可以更改ONTAP Select集群網路配置嗎？
ONTAP Select Deploy 使用可透過 UI、CLI 或 REST API 提供的叢集刷新操作識別以下ONTAP Select叢集屬性的變更：

* 網路設定（IP 位址、DNS、NTP、網路遮罩和網關）
* ONTAP Select叢集、節點名稱和版本


也可以識別以下ONTAP Select VM 變更：

* ONTAP Select VM 名稱和狀態變更（例如，線上或離線）
* 主機網路名稱和儲存池名稱更改


升級到ONTAP Select Deploy 2.6 後，任何已部署但原始配置未發生變更的ONTAP Select叢集均可支援這些變更。換句話說，如果上述ONTAP Select叢集屬性是使用 System Manager 或 vCenter 變更的，那麼升級到ONTAP Select Deploy 2.6 將無法修正這些不一致問題。必須先回滾ONTAP Select屬性更改， ONTAP Select Deploy 才能將其唯一元資料新增至每個ONTAP Select虛擬機器。

.安裝後可以更改ONTAP Select Deploy 網路配置嗎？
不支援在 Deploy 實例在環境中運行後修改其網路詳細資訊。更多信息，請參閱知識庫文章。link:https://kb.netapp.com/onprem/ontap/ONTAP_Select/Modifying_DNS_configuration_of_ONTAP_Deploy_instance["修改ONTAP Deploy 實例的 DNS 配置"^] 。

.Deploy 如何偵測ONTAP Select許可證是否已續約？
所有許可證的方法都是相同的，但具體細節取決於它是容量層許可證還是容量池許可證。

* ONTAP Select Deploy 會偵測是否透過從NetApp購買更新的授權文件來續約許可證和支援合約。許可證文件（.NLF）包含容量、開始日期和結束日期；並且是在…產生的。link:https://mysupport.netapp.com/site/["NetApp支援站點"^]然後更新到部署伺服器。
+

NOTE: 您可以使用 *Add* 和 *Update* 函數將 NLF 載入到 Deploy 伺服器。*Add* 函數用於向伺服器添加新的許可證，而 *Update* 函數用於更新現有文件，其中包含容量、節點許可證（標準版、高級版、高級 XL）、支援開始和結束日期（容量層許可證）或訂閱開始和結束日期（容量池許可證）等資訊。

+

CAUTION: 請勿嘗試修改許可證文件。否則，安全密鑰將失效，許可證也將失效。

* *容量層許可證*是與ONTAP Select節點序號綁定的每節點永久許可證。它隨單獨的支援合約出售。雖然該許可證是永久許可證，但必須續約支援合約才能存取ONTAP Select升級並獲得NetApp技術支援的協助。更改許可證參數（例如容量或節點大小）也需要有效的支援合約。
+
購買容量層許可證更新、參數變更或支援合約續約時，訂單中需要包含節點序號。容量層節點序號長度為 9 位數字，以數字「32」開頭。

+
購買完成並產生許可證文件後，將使用*更新*功能將其上傳到部署伺服器。

* *容量池授權*是一種訂閱，允許使用特定容量池和節點大小（標準、進階、進階 XL）來部署一個或多個叢集。此訂閱包含指定期限的授權使用權和支援服務。許可證使用權和支援合約均有明確的開始和結束日期。


.Deploy 如何偵測節點是否已續約授權或支援合約？
購買、產生和上傳更新的許可證文件是 Deploy 偵測續約許可證和支援合約的方式。

如果容量層支援合約的結束日期已過，節點可以繼續運行，但您將無法下載和安裝ONTAP更新，也無法在未先更新支援合約的情況下致電NetApp技術支援尋求協助。

如果容量池訂閱失效，系統會先警告您，但 30 天后，如果系統關閉，它將不會重新啟動，直到在 Deploy 伺服器上安裝更新的訂閱。



== 儲存

有幾個問題和答案涉及存儲。

.單一ONTAP Select Deploy 實例是否可以在 ESX 和 KVM 上建立叢集？
是的。ONTAP Select Deploy 可以安裝在 KVM 或 ESX 上，且兩種安裝方式都可以在任一虛擬機器管理程式上建立ONTAP Select叢集。

.ESX 上的ONTAP Select是否需要 vCenter？
如果 ESX 主機已取得正確許可，則無需由 vCenter Server 管理 ESX 主機。但是，如果主機由 vCenter Server 管理，則必須配置ONTAP Select Deploy 才能使用該 vCenter Server。換句話說，如果ESX 主機正由 vCenter Server 主動管理，則無法在ONTAP Select Deploy 中將其配置為獨立主機。請注意， ONTAP Select Deploy 虛擬機器依賴 vCenter 來追蹤由於 vMotion 或 VMware HA 事件而在 ESXi 主機之間進行的所有ONTAP Select虛擬機遷移。

.什麼是軟體 RAID？
ONTAP Select可以使用不含硬體 RAID 控制器的伺服器。在這種情況下，RAID 功能透過軟體實現。使用軟體 RAID 時，SSD 和 NVMe 硬碟均支援。 ONTAPONTAP Select啟動磁碟和核心磁碟仍必須位於虛擬化分割區（儲存池或資料儲存）內。 ONTAPONTAP Select使用 RD2（根-資料-資料分區）對 SSD 進行分區。因此， ONTAP Select根分區與資料聚合位於相同的實體主軸上。但是，根聚合以及啟動和核心虛擬化磁碟不計入容量許可證。

AFF/ FAS上可用的所有 RAID 方法也適用於ONTAP Select。這包括 RAID 4、 RAID DP和RAID-TEC。所需的最低 SSD 數量取決於所選的 RAID 配置類型。最佳實務要求至少有一個備用磁碟。備用磁碟和奇偶校驗磁碟不計入容量許可證。

.軟體 RAID 與硬體 RAID 配置有何不同？
軟體 RAID 是ONTAP軟體堆疊中的一個層。軟體 RAID 提供更強的管理控制能力，因為實體磁碟機已分割，並在ONTAP Select虛擬機器中作為原始磁碟使用。而硬體 RAID 通常提供一個大型 LUN，然後可以將其分割出來以建立在ONTAP Select中顯示的 VMDISK。軟體 RAID 是一個可選功能，可以取代硬體 RAID 使用。

軟體 RAID 的一些要求如下：

* 支援 ESX 和 KVM
+
** 從ONTAP Select 9.14.1 開始，已復原對 KVM 虛擬機器管理程式的支援。先前， ONTAP Select 9.10.1 已移除對 KVM 虛擬機器管理程式的支援。


* 支援的實體磁碟大小：200GB – 32TB
* 僅支援 DAS 配置
* 支援 SSD 或 NVMe
* 需要 Premium 或 Premium XL ONTAP Select許可證
* 硬體 RAID 控制器應該不存在或被停用，或應該在 SAS HBA 模式下執行
* 必須對系統磁碟使用基於專用 LUN 的 LVM 儲存池或資料儲存：核心轉儲、啟動/ NVRAM和介體。


.ONTAP Select for KVM 是否支援多個 NIC 綁定？
在 KVM 上安裝時，必須使用單一綁定和單橋接。具有兩個或四個實體連接埠的主機應將所有連接埠設定為相同綁定。

.ONTAP Select如何報告或警報虛擬機器管理程式主機中發生故障的實體磁碟或 NIC？ONTAP Select是否從虛擬機器管理程式中檢索此訊息，還是應在虛擬機器管理程式層級設定監控？
使用硬體 RAID 控制器時， ONTAP Select基本上無法感知底層伺服器問題。如果伺服器按照我們的最佳實踐進行配置，則應該存在一定程度的冗餘。我們建議使用 RAID 5/6 來應對磁碟機故障。對於軟體 RAID 配置， ONTAP負責發出磁碟故障警報，並在有備用磁碟機的情況下啟動磁碟機重建。

您應該至少使用兩個實體網路卡，以避免網路層出現單點故障。 NetAppNetApp為資料、管理和內部連接埠群組配置網路卡綁定和綁定，並在綁定或綁定中包含兩個或更多上行鏈路。此類設定可確保在發生任何上行鏈路故障時，虛擬交換機會將流量從故障上行鏈路轉移到網卡綁定中正常的上行鏈路。有關推薦網路配置的詳細信息，請參閱link:reference_plan_best_practices.html#networking["最佳實務總結：網絡"]。

對於雙節點或四節點集群，所有其他錯誤均由ONTAP HA 處理。如果需要更換虛擬機器管理程式伺服器，並且需要使用新伺服器重建ONTAP Select集群，請參閱_我可以恢復ONTAP Select節點嗎？ _。

.我可以恢復ONTAP Select節點嗎？
如果您需要復原ONTAP Select節點（例如，如果ONTAP Select VM 或主機完全遺失或單節點叢集被意外刪除），請聯絡NetApp技術支援。更多信息，請參閱知識庫文章。link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-KBs/ONTAP_Select_node_VM_recovery_in_case_of_disaster["災難發生時ONTAP Select節點虛擬機器恢復"^] 。

.ONTAP Select支援的最大資料儲存庫大小是多少？
所有配置（包括 vSAN）都支援每個ONTAP Select節點 400TB 的儲存。

在大於支援的最大大小的資料儲存上安裝時，必須在產品設定期間使用容量上限。

.如何增加ONTAP Select節點的容量？
ONTAP Select Deploy 包含一個儲存新增工作流程，支援在ONTAP Select節點上執行容量擴充操作。您可以使用相同資料儲存庫中的空間（如果仍有可用空間）來擴展管理的存儲，也可以從單獨的資料儲存庫中新增空間。不支援在同一聚合中混合使用本機資料儲存庫和遠端資料儲存庫。

儲存添加也支援軟體 RAID。但是，對於軟體 RAID，必須為ONTAP Select虛擬機器添加額外的實體磁碟機。在這種情況下，儲存添加類似於管理FAS或AFF陣列。在使用軟體 RAID 為ONTAP Select節點新增儲存空間時，必須考慮 RAID 群組大小和磁碟機大小。

.ONTAP Select是否支援 vSAN 或外部陣列類型資料儲存？
ONTAP Select Deploy 和ONTAP Select for ESX 支援使用 vSAN 或外部陣列類型的資料儲存作為其儲存池來配置ONTAP Select單節點叢集。

ONTAP Select Deploy 和ONTAP Select for KVM 支援使用外部陣列上的共用邏輯儲存池類型設定ONTAP Select單節點叢集。儲存池可以基於 iSCSI 或 FC/FCoE。不支援其他類型的儲存池。

支援共享儲存上的多節點 HA 叢集。

.ONTAP Select是否支援 vSAN 或其他共用外部儲存（包括一些 HCI 堆疊）上的多節點叢集？
ESX 和 KVM 皆支援使用外部儲存（多節點 vNAS）的多節點叢集。不支援在同一叢集中混合使用虛擬機器管理程式。共享儲存上的 HA 架構仍然意味著 HA 對中的每個節點都擁有其配對資料的鏡像副本。然而，與依賴 VMware HA 或 KVM Live Motion 的單節點叢集相比，多節點叢集具有ONTAP無中斷運作的優勢。

儘管ONTAP Select Deploy 增加了在同一台主機上部署多個ONTAP Select虛擬機的支持，但它不允許這些實例在叢集建立期間成為同一個ONTAP Select叢集的一部分。對於 ESX 環境， NetApp建議建立虛擬機器反關聯性規則，以便 VMware HA 不會嘗試將多個ONTAP Select虛擬機器從同一個ONTAP Select叢集移轉到單一 ESX 主機。此外，如果ONTAP Select Deploy 偵測到ONTAP Select虛擬機的管理（使用者啟動）vMotion 或即時遷移違反了我們的最佳實踐，例如兩個ONTAP Select節點最終位於同一實體主機上，則ONTAP Select Deploy 會在 Deploy UI 和日誌中發出警報。 ONTAPONTAP Select Deploy 獲知ONTAP Select虛擬機器位置的唯一方式是透過叢集刷新操作，這是ONTAP Select Deploy 管理員必須啟動的手動操作。ONTAP Select Deploy 中沒有啟用主動監控的功能，警報只能透過 Deploy UI 或日誌查看。換句話說，此警報無法轉發到集中監控基礎架構。

.ONTAP Select是否支援 VMware 的 NSX VXLAN？
支援 NSX-V VXLAN 連接埠群組。對於多節點 HA（包括ONTAP MetroCluster SDS），請確保將內部網路 MTU 配置為 7500 到 8900 之間（而不是 9000），以適應 VXLAN 開銷。內部網路 MTU 可以在叢集部署期間使用ONTAP Select Deploy 配置。

.ONTAP Select是否支援 KVM 即時遷移？
在外部陣列儲存池上執行的ONTAP Select VM 支援 virsh 即時遷移。

.我需要ONTAP Select Premium 來支援 vSAN AF 嗎？
不，無論外部陣列或 vSAN 配置是否全是閃存，所有版本均受支援。

.支援哪些 vSAN FTT/FTM 設定？
Select 虛擬機器繼承了 vSAN 資料儲存的儲存策略，並且對 FTT/FTM 設定沒有任何限制。但是，請注意，根據 FTT/FTM 設置， ONTAP Select虛擬機器的大小可能顯著大於其設定期間配置的容量。 ONTAPONTAP Select使用在設定期間建立的厚置零 VMDK。為了避免影響使用相同共用資料儲存的其他虛擬機，請務必在資料儲存中提供足夠的可用容量，以容納根據 Select 容量和 FTT/FTM 設定得出的實際 Select 虛擬機大小。

.如果多個ONTAP Select節點屬於不同的 Select 集群，它們可以在同一主機上運行嗎？
可以在同一台主機上配置多個ONTAP Select節點（僅適用於 vNAS 配置），前提是這些節點不屬於同一個ONTAP Select叢集。 DAS配置不支援此操作，因為同一實體主機上的多個ONTAP Select節點會競爭對 RAID 控制器的存取權限。

.您是否可以讓具有單一 10GE 連接埠的主機運行ONTAP Select，並且它是否適用於 ESX 和 KVM？
您可以使用單一 10GE 連接埠連接到外部網路。但是， NetApp建議您僅在空間受限的小型環境中使用此方法。 ESX和 KVM 均支援此功能。

.您需要運行哪些額外的流程才能在 KVM 上進行即時遷移？
您必須在參與即時遷移的每台主機上安裝並執行開源 CLVM 和 Pacemaker (pcs) 元件。這是在每台主機上存取相同磁碟區組所必需的。



== vCenter

有幾個問題和答案與 VMware vCenter 有關。

.ONTAP Select Deploy 如何與 vCenter 通訊以及應該開啟哪些防火牆連接埠？
ONTAP Select Deploy 使用 VMware VIX API 與 vCenter、ESX 主機或兩者進行通訊。文件指出，與 vCenter Server 或 ESX 主機的初始連線是使用 TCP 連接埠 443 上的 HTTPS/SOAP 建立的。這是用於透過 TLS/SSL 進行安全 HTTP 的連接埠。其次，在 TCP 連接埠 902 上的套接字上開啟與 ESX 主機的連線。透過此連線傳輸的資料使用 SSL 加密。此外， ONTAP Select Deploy 還存在以下問題： `PING`命令用於驗證您指定的 IP 位址上是否有 ESX 主機回應。

ONTAP Select Deploy 還必須能夠與ONTAP Select節點和叢集管理 IP 位址進行通信，如下所示：

* 平
* SSH（連接埠 22）
* SSL（連接埠 443）


對於雙節點集群， ONTAP Select Deploy 託管集群郵箱。每個ONTAP Select節點必須能夠透過 iSCSI（連接埠 3260）存取ONTAP Select Deploy。

對於多節點集群，內部網路必須完全開放（無 NAT 或防火牆）。

.ONTAP Select Deploy 需要哪些 vCenter 權限來建立ONTAP Select叢集？
所需的 vCenter 權限清單請參閱此處：link:reference_plan_ots_vcenter.html["VMware vCenter 伺服器"] 。



== HA 和集群

有幾個問題和答案涉及 HA 對和集群。

.四節點、六節點或八節點叢集與雙節點ONTAP Select叢集有什麼差別？
與主要使用ONTAP Select Deploy 虛擬機器建立叢集的四節點、六節點和八節點叢集不同，雙節點叢集持續依賴ONTAP Select Deploy 虛擬機器實作 HA 仲裁。如果ONTAP Select Deploy 虛擬機器不可用，則故障轉移服務將被停用。

.什麼是MetroCluster SDS？
MetroCluster SDS 是一種低成本的同步複製選項，屬於NetApp的MetroCluster業務連續性解決方案類別。它僅適用於ONTAP Select，而NetApp MetroCluster則適用於FAS混合快閃記憶體、 AFF和NetApp Private Storage for Cloud。

.MetroCluster SDS 與NetApp MetroCluster有何不同？
MetroCluster SDS 提供同步複製解，屬於NetApp MetroCluster解。然而，主要區別在於支援的距離（約 10 公里 vs. 300 公里）和連接類型（僅支援 IP 網絡，不支援 FC 和 IP）。

.雙節點ONTAP Select集群和雙節點ONTAP MetroCluster SDS 之間有什麼區別？
雙節點叢集是指兩個節點位於同一資料中心，且彼此相距 300 公尺以內的叢集。通常，兩個節點都透過交換器間連結連接到同一台或一組網路交換器。

雙節點MetroCluster SDS 是指節點在物理上相互隔離（不同房間、不同建築或不同資料中心）的集群，每個節點的上行鏈路連接到單獨的網路交換器。雖然MetroCluster SDS 不需要專用硬件，但該環境應滿足延遲（5 毫秒 RTT 和 5 毫秒抖動，總延遲不超過 10 毫秒）和物理距離（10 公里）方面的一系列最低要求。

MetroCluster SDS 是一項進階功能，需要 Premium 或 Premium XL 授權。 Premium授權支援建立小型和中型虛擬機器以及 HDD 和 SSD 媒體。所有這些配置均受支援。

.ONTAP MetroCluster SDS 是否需要本地儲存（DAS）？
ONTAP MetroCluster SDS 支援所有類型的儲存配置（DAS 和 vNAS）。

.ONTAP MetroCluster SDS 是否支援軟體 RAID？
是的，KVM 和 ESX 上的 SSD 媒體都支援軟體 RAID。

.ONTAP MetroCluster SDS 是否同時支援 SSD 和旋轉介質？
是的，雖然需要高級許可證，但該許可證支援小型和中型虛擬機器以及 SSD 和旋轉媒體。

.ONTAP MetroCluster SDS 是否支援四節點及更大的叢集大小？
不可以，只有具有調解器的雙節點叢集才能配置為MetroCluster SDS。

.ONTAP MetroCluster SDS 有哪些要求？
要求如下：

* 三個資料中心（一個用於ONTAP Select Deploy Mediator，另一個用於每個節點）。
* 5ms RTT 和 5ms 抖動，最大總計 10ms， ONTAP Select節點之間的最大物理距離為 10km。
* ONTAP Select Deploy Mediator 與每個ONTAP Select節點之間的 RTT 為 125ms，頻寬至少為 5Mbps。
* Premium 或 Premium XL 許可證。


.ONTAP Select是否支援 vMotion 或 VMware HA？
在 vSAN 資料儲存或外部陣列資料儲存（換句話說，vNAS 部署）上執行的ONTAP Select VM 支援 vMotion、DRS 和 VMware HA 功能。

.ONTAP Select是否支援 Storage vMotion？
所有配置均支援 Storage vMotion，包括單節點和多節點ONTAP Select叢集以及ONTAP Select Deploy 虛擬機器。 StoragevMotion 可用於在不同 VMFS 版本（例如，從 VMFS 5 遷移到 VMFS 6）之間遷移ONTAP Select或ONTAP Select Deploy 虛擬機，但不限於此用例。最佳做法是在啟動 Storage vMotion 作業之前關閉虛擬機器。在 Storage vMotion 作業完成後， ONTAP Select Deploy 必須發出下列操作：

[listing]
----
cluster refresh
----
請注意，不同類型的資料儲存之間不支援 Storage vMotion 操作。換句話說，不支援 NFS 類型資料儲存與 VMFS 資料儲存之間的 Storage vMotion 操作。通常，不支援外部資料儲存與 DAS 資料儲存之間的 Storage vMotion 操作。

.ONTAP Select節點之間的 HA 流量能否透過不同的 vSwitch 和/或隔離的實體連接埠運作和/或使用 ESX 主機之間的點對點 IP 纜線運作？
不支援這些配置。 ONTAPONTAP Select無法查看承載客戶端流量的實體網路上行鏈路的狀態。因此， ONTAP Select依賴 HA 心跳偵測來確保虛擬機器可同時供用戶端及其對等節點存取。當物理連接丟失時，HA 心跳檢測會導致自動故障轉移到另一個節點，這是所需的行為。

將 HA 流量隔離在單獨的實體基礎架構上可能會導致 Select VM 能夠與其對等虛擬機器通信，但無法與其用戶端通訊。這會阻止自動 HA 流程，並導致資料不可用，直到呼叫手動故障轉移為止。



== 仲介服務

有幾個問題和答案涉及調解服務。

.什麼是調解員服務？
雙節點叢集持續依賴ONTAP Select Deploy 虛擬機器實作 HA 仲裁。參與雙節點 HA 仲裁協商的ONTAP Select Deploy 虛擬機器稱為「調解器虛擬機器」。

.Mediator 服務可以是遠端的嗎？
是的。ONTAP Select Deploy 可作為雙節點 HA 對的調解器，支援高達 500 毫秒 RTT 的 WAN 延遲，並且需要至少 5Mbps 的頻寬。

.Mediator 服務使用什麼協定？
中介器流量為 iSCSI，源自ONTAP Select節點管理 IP 位址，終止於ONTAP Select Deploy IP 位址。請注意，使用雙節點叢集時，不能將 IPv6 用於ONTAP Select節點管理 IP 位址。

.我可以將一個 Mediator 服務用於多個雙節點 HA 叢集嗎？
是的。每個ONTAP Select Deploy 虛擬機器都可以作為最多 100 個雙節點ONTAP Select叢集的通用調解器服務。

.部署後，Mediator 服務位置可以更改嗎？
是的。可以使用另一個ONTAP Select Deploy 虛擬機器來託管調解器服務。

.ONTAP Select是否支援帶有（或不附帶）調解器的延伸叢集？
擴展 HA 部署模型僅支援具有調解器的雙節點叢集。
