---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: 在規劃ONTAP Select部署時，您應該考慮幾個一般要求。 
---
= ONTAP Select要求與規劃注意事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在規劃ONTAP Select部署時，您應該考慮幾個一般要求。



== KVM 所需的 Linux 知識與技能

具有 KVM 虛擬機器管理程式的 Linux 是一個複雜的工作環境。在 KVM 上部署ONTAP Select之前，您必須具備必要的知識和技能。

Linux 伺服器發行版:: 您應該熟悉用於ONTAP Select部署的特定 Linux 發行版。具體來說，您應該能夠執行以下任務：
+
--
* 安裝 Linux 發行版
* 使用 CLI 設定係統
* 新增軟體包以及任何依賴項


--


有關準備 Linux 伺服器的更多資訊（包括所需的設定和軟體包），請參閱主機設定清單。請參閱目前支援的 Linux 發行版的虛擬機器管理程式要求。

KVM部署與管理:: 您應該熟悉常規虛擬化概念。此外，在 KVM 環境中安裝和管理ONTAP Select時，您必須使用幾個 Linux CLI 命令：
+
--
* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`


--
網路和 Open vSwitch 配置:: 您應該熟悉網路概念和網路交換器的配置。此外，您也應該具備使用 Open vSwitch 的經驗。在 KVM 環境中設定ONTAP Select網路時，必須使用下列網路指令：
+
--
* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


--




== 集群大小及相關考慮

您應考慮幾個與叢集大小相關的規劃問題。

叢集中的節點數:: ONTAP Select叢集由一個、兩個、四個、六個或八個節點組成。您應該根據應用程式需求確定叢集的大小。例如，如果企業部署需要 HA 功能，則應使用多節點叢集。
專用與共置:: 根據應用程式類型，您應該確定部署是遵循專用模型還是共置模型。請注意，由於工作負載的多樣性和更緊密的集成，共置模型可能更複雜。




== 虛擬機器管理程序主機注意事項

您應考慮幾個與虛擬機器管理程式主機相關的規劃問題。


CAUTION: 除非NetApp支援人員指示，否則不應直接修改ONTAP Select虛擬機器的配置。只能透過 Deploy 管理實用程式配置和修改虛擬機器。未經NetApp支援人員協助，在 Deploy 實用程式之外對ONTAP Select虛擬機器進行更改可能會導致虛擬機器故障並無法使用。

獨立於虛擬機器管理程序:: ONTAP Select和ONTAP Select Deploy 管理實用程式皆獨立於虛擬機器管理程式。兩者都支援以下虛擬機器管理程式。
+
--
* VMware ESXi
* 基於核心的虛擬機器（KVM）


--



NOTE: 從ONTAP Select 9.14.1 開始，已復原對 KVM 虛擬機器管理程式的支援。先前， ONTAP Select 9.10.1 中已移除在 KVM 虛擬機管理程式上部署新叢集的支持，而ONTAP Select 9.11.1 中已移除對管理現有 KVM 叢集和主機（離線或移除除外）的支援。

有關受支援平台的更多詳細信息，請參閱特定於虛擬機器管理程序的規劃資訊和發行說明。

ONTAP Select節點和管理實用程式的虛擬機器管理程序:: Deploy 管理實用程式和ONTAP Select節點均以虛擬機器形式運作。您為 Deploy 實用程式所選擇的虛擬機器管理程式與您為ONTAP Select節點所選擇的虛擬機器管理程式無關。您可以完全靈活地將兩者配對：
+
--
* 在 VMware ESXi 上執行的部署實用程式可以在 VMware ESXi 或 KVM 上建立和管理ONTAP Select叢集
* 在 KVM 上執行的部署實用程式可在 VMware ESXi 或 KVM 上建立和管理ONTAP Select叢集


--
每個主機有一個或多個ONTAP Select節點實例:: 每個ONTAP Select節點都作為專用虛擬機器運作。您可以在同一虛擬機器管理程式主機上建立多個節點，但有下列限制：
+
--
* 單一ONTAP Select叢集中的多個節點不能在同一台主機上運作。特定主機上的所有節點必須來自不同的ONTAP Select叢集。
* 您必須使用外部儲存。
* 如果使用軟體 RAID，則只能在主機上部署一個ONTAP Select節點。


--
叢集內節點的虛擬機器管理程式一致性:: ONTAP Select叢集中的所有主機必須執行相同版本的虛擬機器管理程式軟體。
每個主機上的實體連接埠數量:: 您必須將每個主機配置為使用一個、兩個或四個實體連接埠。儘管您可以靈活地配置網路端口，但應盡可能遵循以下建議：
+
--
* 單節點叢集中的主機應該有兩個實體連接埠。
* 多節點叢集中的每個主機應該有四個實體端口


--
將ONTAP Select與基於ONTAP硬體的叢集集成:: 您無法將ONTAP Select節點直接新增至基於ONTAP硬體的叢集。但是，您可以選擇在ONTAP Select叢集和基於硬體的ONTAP叢集之間建立叢集對等關係。




== 儲存注意事項

您應考慮幾個與主機儲存相關的規劃問題。

RAID 類型:: 在 ESXi 上使用直接連接儲存 (DAS) 時，您應該決定要使用本機硬體 RAID 控制器或ONTAP Select隨附的軟體 RAID 功能。如果您使用軟體 RAID，請參閱link:reference_plan_ots_storage.html["儲存和 RAID 注意事項"]了解更多。
本地儲存:: 使用 RAID 控制器管理的本機儲存時，您必須決定以下內容：
+
--
* 是否使用一個或多個 RAID 群組
* 是否使用一個或多個 LUN


--
外部存儲:: 使用ONTAP Select vNAS 解決方案時，您必須確定遠端資料儲存庫的位置以及存取方式。 ONTAPONTAP Select vNAS 支援以下配置：
+
--
* VMware vSAN
* 通用外部儲存陣列


--
估算所需儲存空間:: 您應該確定ONTAP Select節點所需的儲存容量。取得包含儲存容量的許可證時需要此資訊。有關更多信息，請參閱存儲容量限制。



NOTE: ONTAP Select儲存容量對應於連接到ONTAP Select虛擬機器的資料磁碟的總允許大小。

生產部署的授權模型:: 您必須為生產環境中部署的每個ONTAP Select叢集選擇容量層或容量池許可模式。有關更多信息，請參閱“許可證”部分。




== 使用憑證儲存進行身份驗證

ONTAP Select Deploy 憑證儲存是一個保存帳戶資訊的資料庫。 Deploy使用帳戶憑證在叢集建立和管理過程中執行主機驗證。您應該了解如何在規劃ONTAP Select部署時使用憑證儲存。


NOTE: 帳戶資訊使用高級加密標準 (AES) 加密演算法和 SHA-256 雜湊演算法安全地儲存在資料庫中。

憑證類型:: 支援以下類型的憑證：
+
--
* 主持人
+
*host* 憑證用於在將ONTAP Select節點直接部署到 ESXi 或 KVM 時對虛擬機器管理程式主機進行驗證。

* vCenter
+
當主機由 VMware vCenter 管理時，*vcenter* 憑證用於在將ONTAP Select節點部署到 ESXi 的過程中對 vCenter 伺服器進行驗證。



--
使用權:: 在使用 Deploy 執行常規管理任務（例如新增虛擬機器管理程式主機）時，可以從內部存取憑證儲存。您也可以直接透過 Deploy Web 使用者介面和 CLI 管理憑證儲存。


.相關資訊
* link:reference_plan_ots_storage.html["儲存和 RAID 注意事項"]

