---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: 您可以使用命令列介面將 Deploy 管理公用程式的現有實例遷移到新的虛擬機器。 
---
= 將ONTAP Select Deploy 實例遷移到新的虛擬機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用命令列介面將 Deploy 管理公用程式的現有實例遷移到新的虛擬機器。

此過程是基於建立一個使用原始虛擬機器配置資料的新虛擬機器。新虛擬機器和原始虛擬機器必須執行相同版本和發行版的 Deploy 實用程式。您無法遷移到其他版本和發行版的 Deploy 實用程式。



== 步驟 1：備份部署設定數據

在遷移虛擬機器的過程中，您必須建立 Deploy 設定資料的備份。部署ONTAP Select叢集後，您也應該建立備份。資料將保存到加密檔案中，您可以將其下載到本機工作站。

.開始之前
* 確保 Deploy 在備份作業期間沒有執行任何其他任務。
* 儲存原始的 Deploy 虛擬機器映像。
+

CAUTION: 在此過程的稍後部分，當您將 Deploy 設定資料從原始虛擬機器還原到新虛擬機器時，需要原始 Deploy 虛擬機器映像。



.關於此任務
您建立的備份檔案會擷取虛擬機器的所有設定資料。這些數據描述了部署環境的各個方面，包括ONTAP Select集群。

.步驟
. 使用管理員帳戶透過 SSHSign inDeploy 實用程式 CLI。
. 建立 Deploy 設定資料的備份，該備份儲存在 Deploy 伺服器的內部目錄中：
+
[source, cli]
----
deploy backup create
----
. 出現提示時，請提供備份密碼。
+
備份檔案根據密碼加密。

. 顯示系統中可用的備份：
+
[source, cli]
----
deploy backup show -detailed
----
. 根據「*建立*」欄位中的日期選擇您的備份檔案並記錄「*下載 URL*」值。
+
您可以透過 URL 存取備份檔案。

. 使用 Web 瀏覽器或公用程式（例如 Curl），透過 URL 將備份檔案下載到本機工作站。




== 步驟 2：安裝 Deploy 虛擬機器的新實例

您必須建立 Deploy 虛擬機器的新實例，並使用原始虛擬機器的設定資料對其進行更新。

.開始之前
您必須熟悉在 VMware 環境中下載和部署ONTAP Select Deploy 虛擬機器的步驟。

.關於此任務
此任務以高層次進行描述。

.步驟
. 建立 Deploy 虛擬機器的新實例：
+
.. 下載虛擬機器映像。
.. 部署虛擬機器並配置網路介面。
.. 使用 SSH 存取 Deploy 實用程式。




.相關資訊
link:task_install_deploy.html["安裝ONTAP Select Deploy"]



== 步驟 3：將部署設定資料還原到新的虛擬機

您必須將設定資料從原始 Deploy 公用程式虛擬機器還原到新的虛擬機器。這些資料位於一個檔案中，您必須從本機工作站上傳該檔案。

.開始之前
您必須擁有先前備份的設定資料。該資料包含在單一文件中，並且必須在您的本機工作站上可用。

.步驟
. 在本機工作站的命令 shell 中，使用 sftp 公用程式將備份檔案上傳到 Deploy 虛擬機，如下例所示：
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. 使用管理員帳戶透過 SSHSign inDeploy 實用程式 CLI。
. 恢復配置資料：
+
[source, cli]
----
deploy backup restore -path <path_name> -filename <file_name>
----
+
範例命令

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


