---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 您可以使用命令列介面就地升級現有的 Deploy 實用程式虛擬機器。 
---
= 升級ONTAP Select Deploy 實例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 ONTAP ONTAP Select ONTAP Select Deploy 實用程式虛擬機器。

.開始之前
確保在升級期間不使用ONTAP Select Deploy 執行任何其他任務。有關升級ONTAP Select Deploy 實用程式的資訊和限制，請參閱目前發行說明。

[NOTE]
====
如果您安裝了ONTAP Select Deploy 管理公用程式的舊實例，則應升級至目前版本。 ONTAPONTAP Select節點和ONTAP Select Deploy 元件將單獨升級。看link:concept_adm_upgrading_nodes.html["升級ONTAP Select節點"^]更多詳情請見下文。

您可以從 ONTAP ONTAP Select ONTAP Select Deploy 9.17.1。若要從ONTAP Select Deploy 9.14.1 或更早版本升級，請查看ONTAP Select版本的發行說明。

====


== 步驟 1：下載軟體包

若要開始升級流程，請從下列位置下載對應的ONTAP Select Deploy 虛擬機器升級檔案：link:https://mysupport.netapp.com/site/["NetApp支援站點"^] 。升級包格式為單一壓縮檔。

.步驟
. 訪問link:https://mysupport.netapp.com/site/["NetApp支援站點"^]使用網頁瀏覽器，從「下載」選單中選擇「下載」。
. 向下捲動並選擇 * ONTAP Select Deploy Upgrade*。
. 選擇所需的升級包版本。
. 查看最終用戶許可協議 (EULA) 並選擇*接受並繼續*。
. 選擇並下載適當的包，根據您的環境需求回應所有提示。




== 步驟 2：將軟體包上傳到ONTAP Select Deploy 虛擬機

下載軟體包後，您需要將檔案上傳到ONTAP Select Deploy 虛擬機器。

.關於此任務
此任務介紹了一種將檔案上傳到ONTAP Select Deploy 虛擬機器的方法。可能還有其他選項更適合您的環境。

.開始之前
* 驗證升級檔案是否在本機工作站上可用。
* 驗證您是否擁有管理員使用者帳戶的密碼。


.步驟
. 在本地工作站的命令提示字元中，使用 `scp`使用（安全複製協定）實用程式將映像檔上傳到ONTAP Select Deploy 虛擬機，如下範例所示：
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
升級檔案儲存在管理員使用者的主目錄中。



== 步驟3：應用升級包

將升級檔案上傳到ONTAP Select Deploy 虛擬機器後，即可套用升級。

.開始之前
* 驗證升級檔案在ONTAP Select Deploy 實用程式虛擬機器中放置的目錄。
* 驗證在執行升級時ONTAP Select Deploy 未用於執行任何其他任務。


.步驟
. 使用管理員帳戶透過 SSHSign inONTAP Select Deploy 實用程式 CLI。
. 使用適當的目錄路徑和檔案名稱執行升級：
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
範例命令：

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完成後
在升級過程完成之前，系統會要求您建立ONTAP Select Deploy 虛擬機器配置的備份。此外，您應該清除瀏覽器快取，以便可以查看新建立的ONTAP Select Deploy 頁面。
