---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果ONTAP Select Deploy 實用程式因某種原因發生故障或不可用，您將無法管理ONTAP Select節點和叢集。此外，所有雙節點叢集都會失去 HA 功能，因為 Deploy 附帶的調解器服務不可用。如果發生不可復原的故障，您必須復原 Deploy 公用程式執行個體才能復原管理和 HA 功能。 
---
= 恢復雙節點叢集的ONTAP Select Deploy 實用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果ONTAP Select Deploy 實用程式因某種原因發生故障或不可用，您將無法管理ONTAP Select節點和叢集。此外，所有雙節點叢集都會失去 HA 功能，因為 Deploy 附帶的調解器服務不可用。如果發生不可復原的故障，您必須復原 Deploy 公用程式執行個體才能復原管理和 HA 功能。



== 準備恢復部​​署實用程式

在嘗試還原 Deploy 實用程式實例之前，您需要做好準備以確保成功。您必須熟悉若干行政程序並掌握所需資訊。

.步驟
. 確認您可以在虛擬機器管理程式環境中安裝ONTAP Select Deploy 實用程式的新實例。
+
link:task_install_deploy.html["了解如何安裝ONTAP Select Deploy 實用程式"]

. 確認您可以登入ONTAP Select叢集並存取ONTAP叢集 shell (CLI)。
. 確定您是否擁有包含ONTAP Select雙節點叢集的失敗部署公用程式實例的設定資料備份。您可能擁有不包含該叢集的備份。
. 根據所使用的復原程序，驗證是否可以還原部署配置資料的備份。
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["了解如何將部署配置資料還原到新的虛擬機"]

. 您擁有發生故障的原始部署公用程式虛擬機器的 IP 位址。
. 確定採用容量池許可或容量層級許可。如果使用容量池許可，則必須在復原或還原 Deploy 執行個體後重新安裝每個容量池許可證。
. 決定在復原ONTAP Select Deploy 實用程式實例時使用哪個程式。您的決定取決於您是否擁有包含ONTAP Select雙節點叢集的原始故障 Deploy 實用程式的設定資料備份。
+
[cols="35,65"]
|===
| 您是否有包含雙節點叢集的 Deploy 備份？ | 使用恢復程序… 


| 是的 | <<restore-deploy-backup,使用設定備份還原 Deploy 實用程式實例>> 


| 不 | <<restore-and-recover-deploy,重新配置並還原 Deploy 實用程式實例>> 
|===




== 使用設定備份還原 Deploy 實用程式實例

如果您擁有包含雙節點叢集的故障 Deploy 公用程式執行個體的備份，則可以將設定資料還原到新的 Deploy 虛擬機器執行個體。然後，您必須透過對ONTAP Select叢集中的兩個節點執行額外配置來完成復原。

.開始之前
備份包含雙節點叢集的原始部署失敗虛擬機器的設定資料。您必須能夠登入雙節點叢集的ONTAP CLI，並且知道這兩個節點的ONTAP名稱。

.關於此任務
由於您復原的設定備份包含雙節點集群，因此將在新的 Deploy 公用程式虛擬機中重新建立中介 iSCSI 目標和信箱。

.步驟
. 準備ONTAP Select Deploy 實用程式的新實例：
+
.. 安裝新的 Deploy 實用程式虛擬機器。
.. 將 Deploy 設定從先前的備份還原到新的虛擬機器。
+
有關安裝和恢復過程的更多詳細信息，請參閱相關任務。



. Sign inONTAP Select雙節點叢集的ONTAP命令列介面。
. 進入進階權限模式：
+
[source, cli]
----
set adv
----
. 如果新部署虛擬機器的 IP 位址與原部署虛擬機器的 IP 位址不同，請刪除舊的中介 iSCSI 目標並新增目標：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
這 `<ip_address>`參數是新部署虛擬機器的 IP 位址。

+
這些命令允許ONTAP Select節點發現新 Deploy 實用程式虛擬機器上的郵件磁碟。

. 確定中介磁碟的名稱：
+
[source, cli]
----
disk show -container-type mediator
----
. 將郵箱磁碟分配給兩個節點：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 驗證儲存故障轉移是否已啟用：
+
[source, cli]
----
storage failover show
----


.完成後
如果您使用容量池許可，請重新安裝每個容量池許可證。看link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安裝容量池許可證"]更多詳情請見下文。



== 重新配置並還原 Deploy 實用程式實例

如果您沒有包含雙節點叢集的失敗部署公用程式實例的備份，請在新的部署虛擬機器中設定中介 iSCSI 目標和郵件信箱。然後，透過對ONTAP Select叢集中的兩個節點進行額外配置來完成復原。

.開始之前
請確認您已取得新部署公用程式實例的中介目標名稱。您必須能夠登入雙節點叢集的ONTAP CLI，並且知道這兩個節點的ONTAP名稱。

.關於此任務
即使新的 Deploy 虛擬機器不包含雙節點集群，您也可以選擇將設定備份還原到該虛擬機器。由於還原作業不會重新建立雙節點集群，因此您必須透過 Deploy 上的ONTAP Select線上文件網頁，手動將中介 iSCSI 目標和郵件匣新增至新的 Deploy 公用程式實例。您必須能夠登入雙節點集群，並且知道這兩個節點的ONTAP名稱。


NOTE: 復原過程的目標是將雙節點叢集恢復到健康狀態，以便可以執行正常的 HA 接管和交還操作。

.步驟
. 準備ONTAP Select Deploy 實用程式的新實例：
+
.. 安裝新的 Deploy 實用程式虛擬機器。
.. 可以選擇將 Deploy 設定從先前的備份還原到新的虛擬機器。
+
如果您還原先前的備份，新的 Deploy 執行個體將不包含雙節點叢集。有關安裝和恢復過程的更多詳細信息，請參閱相關資訊部分。



. Sign inONTAP Select雙節點叢集的ONTAP命令列介面。
. 進入進階特權模式：
+
[source, cli]
----
set adv
----
. 取得中介 iSCSI 目標名稱：
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 造訪新部署實用程式虛擬機器上的線上文件網頁並使用管理員帳戶登入：
+
`\http://<ip_address>/api/ui`

+
您必須使用 Deploy 虛擬機器的 IP 位址。

. 選擇 *Mediator*，然後選擇 *GET /mediators*。
. 選擇「試用！」以顯示 Deploy 維護的中介器清單。
+
記下所需中介實例的 ID。

. 選擇“中介者”，然後選擇“POST”。
. 提供 mediator_id 的值。
. 選擇旁邊的“型號” `iscsi_target`並填寫名稱值。
+
使用目標名稱作為 iqn_name 參數。

. 選擇「試用！」以建立中介 iSCSI 目標。
+
如果請求成功，您將收到 HTTP 狀態碼 200。

. 如果新 Deploy 虛擬機器的 IP 位址與原始 Deploy 虛擬機器不同，則必須使用ONTAP CLI 刪除舊的調解器 iSCSI 目標並新增新的目標：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
這 `<ip_address>`參數是新部署虛擬機器的 IP 位址。

+
這些命令允許ONTAP Select節點發現新 Deploy 實用程式虛擬機器上的郵件磁碟。

. 確定中介磁碟的名稱：
+
[source, cli]
----
disk show -container-type mediator
----
. 將郵箱磁碟分配給兩個節點：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 驗證儲存故障轉移是否已啟用：
+
[source, cli]
----
storage failover show
----


.完成後
如果您使用容量池許可，請重新安裝每個容量池許可證。看link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安裝容量池許可證"]更多詳情請見下文。
